name: b36944
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: ^0.6.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^2.0.0
#  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.0.0
